'''
Using LLM to combine model outputs
'''
from abc import ABC, abstractmethod
from .select_llm_base_model import get_model

class BaseLLMCombiner(ABC):
    def __init__(self, source_sentences, pred_texts, comb_model_name='mistral-7b'):
        self.comb_model = get_model(comb_model_name)
        self.combined_texts = self._make_all_changes(source_sentences, pred_texts)
    
    
    def _make_all_changes(self, source_sentences, pred_texts):
        prompts = self._prep_prompts(source_sentences, pred_texts)
        return self.comb_model.predict_all(prompts)
    
    @abstractmethod
    def _prep_prompts(self, source_sentences, pred_texts):
        pass


class SelectionLLMCombiner(BaseLLMCombiner):
    def __init__(self, *args, **kwargs):
        BaseLLMCombiner.__init__(self, *args, **kwargs)

    def _make_all_changes(self, source_sentences, pred_texts):
        prompts = self._prep_prompts(source_sentences, pred_texts)
        selections = self.comb_model.predict_all(prompts)
        return selections # to change

    def _prep_prompts(self, source_sentences, pred_texts):
        preds = list(zip(*pred_texts))
        prompts = [self._prompt(s, ps) for s,ps in zip(source_sentences, preds)]
        return prompts
    
    def _prompt(self, source, preds):
        # out = (
        #     "You are to help with grammatical error correction."
        #     "You will be given a source grammatically incorrect sentence (src) and possible"
        #     "grammatically corrected output sentence options (option), "
        #     "select a single output sentence option that best perform grammatical error correction of the source sentence."
        #     "Make sure you return only the selected output sentence and nothing else.\n"
        #     f"src: {source}\n"
        # )
        out = (
            "Given an input sentence, perform grammatical error correction based on the 3 output sentencess generated by different grammatical error correction systems.\n"
            f"<input>{source}</input>"
            "The different output sentence options are as as follows:\n\n"
        )
        for i, pred in enumerate(preds):
            out += f"<option{i+1}>{pred}</option{i+1}>\n"
        out += f"\n\n"
        out += "Please output the selected best grammatically corrected output sentence as <option?>The selected output sentence</option?>.\n"
        return out

